name: tag

on:
  push:
    tags:
      - "v*"

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Version
      id: get-version
      run: |
        echo ::set-output name=version::${${GITHUB_REF#refs/tags/}:1}
    - name: Update version numbers
      run: |
        echo Branch name is ${GITHUB_REF##*/}
        git config --local user.name "Pathogen Informatics CI"
        git config --local user.email "pathdev@sanger.ac.uk"
        sed -i "s@^process.container\s*=\s*'sangerpathogens/gbs-typer-sanger-nf:.*$@process.container = sangerpathogens/gbs-typer-sanger-nf:${{ steps.get-version.outputs.version }}@g" nextflow.config
#        git commit -am "Updated the version number to ${{ steps.get-version.outputs.version }}"
#        git push
