# Update config version numbers on release tagging.

name: tag

on:
  push:
    tags: "v*"

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Version
      id: get-version
      run: |
        ver=${GITHUB_REF#refs/tags/}
        vernum=${ver:1}
        echo "::set-output name=version::$vernum"
    - name: Update version numbers
      run: |
        echo Tag is ${GITHUB_REF##*/}
        git config --local user.name "Pathogen Informatics CI"
        git config --local user.email "pathdev@sanger.ac.uk"
        git checkout -b tmp-${{ steps.get-version.outputs.version }}
        sed -i "s@gbs-typer-sanger-nf:.*@gbs-typer-sanger-nf:${{ steps.get-version.outputs.version }}'@g" nextflow.config
        git commit -am "Updated the version number to ${{ steps.get-version.outputs.version }}"
        git tag -d v${{ steps.get-version.outputs.version }}
        git tag v${{ steps.get-version.outputs.version }}
        git push -q origin v${{ steps.get-version.outputs.version }}
